name: Deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.x  # or the version you are using

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          force_orphan: true

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: "trinitylog"
          message: "Deployment of my Jekyll blog is complete!"
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
